/* ============================================
   Crearzo — Portfolio Image Data
   All portfolio images organized by category
   ============================================ */

const PORTFOLIO_DATA = [

    // ── LOGOS (79 images) ──────────────────────────────
    { src: "../Logos/Bro Fites final file-01.jpg", category: "logos", title: "Bro Fites Logo" },
    { src: "../Logos/C2bs Logo 1-01.jpg", category: "logos", title: "C2bs Logo" },
    { src: "../Logos/Express Laundry-01.jpg", category: "logos", title: "Express Laundry Logo" },
    { src: "../Logos/Fun tea 2-03.jpg", category: "logos", title: "Fun Tea Logo" },
    { src: "../Logos/Green group-03.jpg", category: "logos", title: "Green Group Logo" },
    { src: "../Logos/jf home made cakes-03.jpg", category: "logos", title: "JF Home Made Cakes Logo" },
    { src: "../Logos/b9b12046-9b66-4a85-9164-6a724dc0e2e2.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/d98ad0da-fea5-45be-bea6-2721a394f520.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-02.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-06.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-07.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-12.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-15.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-16.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-22.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-25.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-26.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-27.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-34.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-38.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-43.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-45.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-48.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-49.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-52.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-57.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-60.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-62.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-63.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-71.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-75.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-76.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-77.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-78.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-79.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-80.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-81.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-82.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-83.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-84.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-85.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-86.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-87.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-88.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-89.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-90.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-91.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-92.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-93.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-94.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-95.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-97.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-98.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-99.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-100.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-101.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-102.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-103.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-104.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-105.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-106.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-107.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-108.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-109.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-110.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-111.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-112.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-113.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-114.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-115.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-121.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-133.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-134.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-135.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-136.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-137.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-143.jpg", category: "logos", title: "Logo Design" },
    { src: "../Logos/Untitled-2-157.jpg", category: "logos", title: "Logo Design" },

    // ── BUSINESS CARDS (5 images) ──────────────────────
    { src: "../Business cards/Untitled-2-03.jpg", category: "business-cards", title: "Business Card Design" },
    { src: "../Business cards/Untitled-2-10.jpg", category: "business-cards", title: "Business Card Design" },
    { src: "../Business cards/Untitled-2-50.jpg", category: "business-cards", title: "Business Card Design" },
    { src: "../Business cards/Untitled-2-64.jpg", category: "business-cards", title: "Business Card Design" },
    { src: "../Business cards/Untitled-2-74.jpg", category: "business-cards", title: "Business Card Design" },

    // ── PACKAGING DESIGN (90 images) ──────────────────
    { src: "../Packing Designs/Babys Tag.jpg", category: "packaging", title: "Baby's Tag Packaging" },
    { src: "../Packing Designs/Blueberry Wafers-.jpg", category: "packaging", title: "Blueberry Wafers Packaging" },
    { src: "../Packing Designs/Dia Sanitary Pads.jpg", category: "packaging", title: "Dia Sanitary Pads Packaging" },
    { src: "../Packing Designs/Ferric dates.png", category: "packaging", title: "Ferric Dates Packaging" },
    { src: "../Packing Designs/Food_Bag_Mockup_Matt_1-1-1152x1536.jpg", category: "packaging", title: "Food Bag Mockup" },
    { src: "../Packing Designs/Mockup 02.jpg", category: "packaging", title: "Packaging Mockup" },
    { src: "../Packing Designs/pain relief herbal oil.jpg", category: "packaging", title: "Pain Relief Herbal Oil Packaging" },
    { src: "../Packing Designs/Sambar Powder copy.jpg", category: "packaging", title: "Sambar Powder Packaging" },
    { src: "../Packing Designs/Sea Food Express.jpg", category: "packaging", title: "Sea Food Express Packaging" },
    { src: "../Packing Designs/Tender cocount 1.jpg", category: "packaging", title: "Tender Coconut Packaging" },
    { src: "../Packing Designs/Tidy Toilet Cleaner.jpg", category: "packaging", title: "Tidy Toilet Cleaner Packaging" },
    { src: "../Packing Designs/tooth powder.jpg", category: "packaging", title: "Tooth Powder Packaging" },
    { src: "../Packing Designs/vasambu 3.jpg", category: "packaging", title: "Vasambu Packaging" },
    { src: "../Packing Designs/Wow Salt.jpg", category: "packaging", title: "Wow Salt Packaging" },
    { src: "../Packing Designs/03.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/1.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/05730a17-e982-423c-8984-004943a82df3.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/0b4b05bd-1b8c-4a71-ae12-88ef84d6e181.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/0e18a749-e2a2-46f5-98a0-566dde066bc5.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/1be8b00a-d239-495c-ab3b-6f71790ea988.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/28f4dee9-700b-497a-81f4-5f41c195f37b.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/34d7dea8-84b6-48a5-94de-68b487f4d7be.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/3cd2c8a7-fe79-4c34-9f9a-60f957993560.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/469ae185-65e3-4d0d-81b8-23df39c08613.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/55708a6c-0810-445a-a6bc-2d68980e7ff3.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/596ad9ae-fc4d-4c0e-b9f2-7e515e10ef2e.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/5bbde7ab-5f2d-4536-bdff-a265a4331803.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/5f12353c-d082-46bb-a51b-278e4d62e945.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/6aecdb47-3427-49d2-98cd-a1bc33143e10.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/78ad4f50-b247-40b4-b4f9-aedafdd6291b.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/78b4e091-fda0-46cc-9af2-e49f1971cb2a.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/7ebdbf97-2e7e-4763-8e8a-2fb776a3058d.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/86db39a2-058c-4635-9997-9f4a4159c98c.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/87f7a0d9-1f63-4f85-be67-760e9c194b93.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/89165ffa-2030-4ddf-99bf-207c6469e596.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/8957c87f-81ee-4c42-841f-a64c72e3e6b7.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/898d7838-46cd-4310-9583-e65a91a53654.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/910834ce-3b62-4f02-8a3d-aa6b8fea2cd5.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/bafd4c61-faff-4358-85c1-989bb5411100.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/be923d6e-0394-43d1-86dc-2b7e8f4e3b86.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/d0af9b60-1ea7-402c-be61-864fbf56a7d4.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/d2ad89ac-ad63-40d5-bc32-8400044823de.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/d43930af-c607-4e13-a623-23aaced127d0.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/d62ba6d2-3a14-43a3-8671-23a11ffd7ef4.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/d90e0ce1-45ef-447a-8939-9667b4bafe69.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/e147014e-07f5-4fd5-81d0-efd77ebbd94b (1).jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/e332b34a-4aa1-4d31-b845-6a52de5db603.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/f42e0b65-0cce-4ff5-887f-c02e0be5f9ca.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/f9bc56d5-8c8a-48c1-a2a6-55b3e4f8c495.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/fd421e8a-c4ab-43d6-b482-9ee0fe1961ef.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-14.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-23.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-24.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-36.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-37.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-39.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-40.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-41.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-42.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-44.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-58.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-59.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-61.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-72.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-73.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-116.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-119.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-123.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-124.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-125.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-126.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-127.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-128.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-129.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-132.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-138.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-139.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-140.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-141.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-142.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-144.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-145.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-146.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-147.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-148.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-149.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-150.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-151.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-152.jpg", category: "packaging", title: "Packaging Design" },
    { src: "../Packing Designs/Untitled-2-153.jpg", category: "packaging", title: "Packaging Design" },

    // ── MENU CARDS (22 images) ─────────────────────────
    { src: "../Menu Cards/Cakes Menu-01.jpg", category: "menu-cards", title: "Cakes Menu Card" },
    { src: "../Menu Cards/28199ca5-82be-474f-b697-ff7810c20e5c.jpg", category: "menu-cards", title: "Menu Card Design" },
    { src: "../Menu Cards/9fff9ce9-66f5-4ba2-ac9b-dd633a52a829.jpg", category: "menu-cards", title: "Menu Card Design" },
    { src: "../Menu Cards/ab9eeef1-8a66-4d8d-9ea2-4fadf52119da.jpg", category: "menu-cards", title: "Menu Card Design" },
    { src: "../Menu Cards/b18f2891-7b40-49cc-8205-3c06368f081a.jpg", category: "menu-cards", title: "Menu Card Design" },
    { src: "../Menu Cards/b5e26c2a-781c-42da-b0dc-040b4bdec7bb.jpg", category: "menu-cards", title: "Menu Card Design" },
    { src: "../Menu Cards/b7da592c-fa7b-4b18-95cf-af02101660e9.jpg", category: "menu-cards", title: "Menu Card Design" },
    { src: "../Menu Cards/e7fbdd26-06c1-4b77-b67d-717cff311f29.jpg", category: "menu-cards", title: "Menu Card Design" },
    { src: "../Menu Cards/e95b320b-3938-4a7e-b35d-b2627272583e.jpg", category: "menu-cards", title: "Menu Card Design" },
    { src: "../Menu Cards/Untitled-2-04.jpg", category: "menu-cards", title: "Menu Card Design" },
    { src: "../Menu Cards/Untitled-2-05.jpg", category: "menu-cards", title: "Menu Card Design" },
    { src: "../Menu Cards/Untitled-2-08.jpg", category: "menu-cards", title: "Menu Card Design" },
    { src: "../Menu Cards/Untitled-2-11.jpg", category: "menu-cards", title: "Menu Card Design" },
    { src: "../Menu Cards/Untitled-2-19.jpg", category: "menu-cards", title: "Menu Card Design" },
    { src: "../Menu Cards/Untitled-2-28.jpg", category: "menu-cards", title: "Menu Card Design" },
    { src: "../Menu Cards/Untitled-2-29.jpg", category: "menu-cards", title: "Menu Card Design" },
    { src: "../Menu Cards/Untitled-2-31.jpg", category: "menu-cards", title: "Menu Card Design" },
    { src: "../Menu Cards/Untitled-2-33.jpg", category: "menu-cards", title: "Menu Card Design" },
    { src: "../Menu Cards/Untitled-2-65.jpg", category: "menu-cards", title: "Menu Card Design" },
    { src: "../Menu Cards/Untitled-2-66.jpg", category: "menu-cards", title: "Menu Card Design" },
    { src: "../Menu Cards/Untitled-2-68.jpg", category: "menu-cards", title: "Menu Card Design" },
    { src: "../Menu Cards/Untitled-2-70.jpg", category: "menu-cards", title: "Menu Card Design" },

    // ── CATALOGS (8 images) ───────────────────────────
    { src: "../Catalogs/0f8f063a-d58b-4bfd-8a98-1c8e28033ec1.jpg", category: "catalogs", title: "Catalog Design" },
    { src: "../Catalogs/11d80388-016c-4c8f-b1bc-569e4ca83c6b.jpg", category: "catalogs", title: "Catalog Design" },
    { src: "../Catalogs/218bc8f8-a70f-43ba-9c3a-b0774157b521.jpg", category: "catalogs", title: "Catalog Design" },
    { src: "../Catalogs/439023ed-ac28-4410-8623-c61a47e74fcc.jpg", category: "catalogs", title: "Catalog Design" },
    { src: "../Catalogs/Untitled-2-46.jpg", category: "catalogs", title: "Catalog Design" },
    { src: "../Catalogs/Untitled-2-47.jpg", category: "catalogs", title: "Catalog Design" },
    { src: "../Catalogs/Untitled-2-53.jpg", category: "catalogs", title: "Catalog Design" },
    { src: "../Catalogs/Untitled-2-54.jpg", category: "catalogs", title: "Catalog Design" },

    // ── POSTERS & BANNERS (16 images) ─────────────────
    { src: "../Poster and Banner/ad-01.jpg", category: "posters", title: "Advertisement Poster" },
    { src: "../Poster and Banner/494be2e8-1e78-495e-a154-26a645bf5ba8.jpg", category: "posters", title: "Poster Design" },
    { src: "../Poster and Banner/710b5d0a-1fef-4493-9ed3-6befff2183ad.jpg", category: "posters", title: "Poster Design" },
    { src: "../Poster and Banner/be69eb4b-3add-4f31-b038-b2c67a72a4bb.jpg", category: "posters", title: "Banner Design" },
    { src: "../Poster and Banner/Untitled-2-09.jpg", category: "posters", title: "Poster Design" },
    { src: "../Poster and Banner/Untitled-2-18.jpg", category: "posters", title: "Poster Design" },
    { src: "../Poster and Banner/Untitled-2-20.jpg", category: "posters", title: "Banner Design" },
    { src: "../Poster and Banner/Untitled-2-21.jpg", category: "posters", title: "Banner Design" },
    { src: "../Poster and Banner/Untitled-2-30.jpg", category: "posters", title: "Poster Design" },
    { src: "../Poster and Banner/Untitled-2-32.jpg", category: "posters", title: "Poster Design" },
    { src: "../Poster and Banner/Untitled-2-51.jpg", category: "posters", title: "Banner Design" },
    { src: "../Poster and Banner/Untitled-2-55.jpg", category: "posters", title: "Poster Design" },
    { src: "../Poster and Banner/Untitled-2-56.jpg", category: "posters", title: "Poster Design" },
    { src: "../Poster and Banner/Untitled-2-67.jpg", category: "posters", title: "Banner Design" },
    { src: "../Poster and Banner/Untitled-2-69.jpg", category: "posters", title: "Poster Design" },
    { src: "../Poster and Banner/Untitled-2-154.jpg", category: "posters", title: "Poster Design" }
];

// Category labels for display
const CATEGORY_LABELS = {
    'all': 'All Work',
    'logos': 'Logos',
    'business-cards': 'Business Cards',
    'packaging': 'Packaging',
    'menu-cards': 'Menu Cards',
    'catalogs': 'Catalogs',
    'posters': 'Posters & Banners'
};
